name: Deploy docs
on: 
  push:
    branches: 
      - main
      - master
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Install Crystal libs
        run: shards install
      - name: Get raylib-cr for install script
        run: git clone https://github.com/sol-vin/raylib-cr
      - name: run install script
        run: sh ./raylib-cr/rsrc/native/ubuntu/install.sh
      - name: Build site
        run: crystal docs
      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
